// android/build.gradle
plugins {
    id 'com.android.library' version '8.7.2'  // 必须指定版本号
}

repositories {
    google()  // 必须添加 Google Maven 仓库
    mavenCentral()
}

android {
    compileSdk 33
    namespace 'com.example.nodejsmobile'

    defaultConfig {
        minSdk 24
        targetSdk 33
    }

   buildTypes {
        release {
            // 显式启用 release 构建
            minifyEnabled false
        }
        debug {
            // 显式启用 debug 构建
            debuggable true
        }
    }
}
